ARG GO_VERSION=1.16.6
FROM golang:${GO_VERSION}-alpine AS builder

RUN mkdir /user && \
    echo 'nobody:x:65534:65534:nobody:/:' > /user/passwd && \
    echo 'nobody:x:65534:' > /user/group

RUN apk update && \
    apk add --no-cache git ca-certificates && \
    update-ca-certificates

# For faster builds
ENV CGO_ENABLED=0

WORKDIR /src
RUN unset GOPATH

# install dependencies
COPY ./go.mod .
COPY ./go.sum .

RUN go mod download
RUN go mod verify

COPY . .

# RUN go test ./...
RUN cd ./example/mongo_crud && go build \
    -installsuffix 'static' \
    -o /app

FROM scratch AS final
COPY --from=builder /user/group /user/passwd /etc/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app /app

EXPOSE 8080

USER nobody:nobody

ENTRYPOINT ["/app"]
